
language: node_js
sudo: required
addons:
    chrome: stable
node_js:
- 9
os: linux
cache:
  yarn: true
branches:
  only:
  - master
  - dev
install:
- |
    npm install
script:
- |
    npm run eslint && npm run stylelint && npm run test
after_success:
- |
    cat ./test/coverage/lcov.info | ./node_modules/.bin/codecov
